# Generated by Django 3.0.7 on 2020-06-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200613_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcodes',
            name='time',
        ),
    ]
