# Generated by Django 3.0.7 on 2020-07-10 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200710_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcodes',
            name='uid',
        ),
        migrations.AddField(
            model_name='passwordresetcodes',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=52),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordresetcodes',
            name='password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='passwordresetcodes',
            name='username',
            field=models.CharField(max_length=36),
        ),
    ]
